const { send } = require("./budget.cjs");
const { isContractRevert } = require("./revert.cjs");
const assert = require("node:assert/strict");
const fs = require("node:fs/promises");
const path = require("node:path");
const hre = require("hardhat");
const { root, context, evidenceRun, deploy, fail } = require("./helpers.cjs");

async function main() {
  const core = await context(hre);
  const rpc = hre.ethers.provider;
  const pair = process.env.PROOF_PAIR_ADDRESS || await core.discoverPair(rpc);
  const pool = await core.readPool(pair, rpc);
  const lp = new hre.ethers.Contract(pool.lpToken, core.TOKEN_ABI, core.signer);
  const before = await lp.balanceOf(core.signer.address);
  if (before === 0n) throw new Error("No usable LP balance. Run testnet:acquire-lp first. Deployment/registration alone is NOT workflow proof.");
  const requested = process.env.PROOF_LP_AMOUNT || "0";
  if (!/^\d+$/.test(requested)) throw new Error("PROOF_LP_AMOUNT must be a nonnegative base-unit integer.");
  const amount = BigInt(requested) || (before > 100n ? before / 100n : 1n);
  if (amount > before || amount > 9223372036854775807n) throw new Error("Requested proof amount exceeds balance or HTS int64.");
  console.log(`Proposed lock cycle: ${process.env.POOLPLEDGE_ADDRESS ? "reuse configured deployment" : "deploy using RPC gas estimate"}; associate LP; approve exactly ${amount} LP base units; deposit to a 90-second self-beneficiary lock; withdraw after maturity. No LP is sold or burned; network fees are additional.`);
  const run = await evidenceRun("lock-cycle", { account: core.account.account, beneficiary: core.signer.address, pool, amount: amount.toString(), beforeBalance: before.toString() });
  let pledge;
  if (process.env.POOLPLEDGE_ADDRESS) pledge = await hre.ethers.getContractAt("PoolPledge", core.address(process.env.POOLPLEDGE_ADDRESS), core.signer);
  else pledge = await deploy(hre, core, run);
  const contractAddress = await pledge.getAddress();
  assert.equal((await pledge.factory()).toLowerCase(), core.TESTNET.factory.toLowerCase());
  run.data.contract = contractAddress;
  await run.save();
  if (await pledge.registeredToken(pair) === hre.ethers.ZeroAddress) await send(hre, core, run, "HTS association of canonical LP", await pledge.registerPair.populateTransaction(pair, {}));
  assert.equal((await pledge.registeredToken(pair)).toLowerCase(), pool.lpToken.toLowerCase());
  await send(hre, core, run, "approve exact LP amount", await lp.approve.populateTransaction(contractAddress, amount, {}));
  assert.equal(await lp.allowance(core.signer.address, contractAddress), amount);
  const beforeEscrow = await lp.balanceOf(contractAddress);
  const beforeLiability = await pledge.totalLocked(pool.lpToken);
  const unlockAt = (await rpc.getBlock("latest")).timestamp + 90;
  const receipt = await send(hre, core, run, "deposit LP into timed escrow", await pledge.createLock.populateTransaction(pair, amount, core.signer.address, unlockAt, {}));
  const event = receipt.logs.map(log => { try { return pledge.interface.parseLog(log); } catch { return null; } }).find(log => log?.name === "Locked");
  assert(event, "Missing Locked event");
  const id = event.args.id;
  run.data.lockId = id.toString();
  run.data.unlockAt = unlockAt;
  await run.save();
  assert.equal(await lp.balanceOf(core.signer.address), before - amount);
  assert.equal(await lp.balanceOf(contractAddress), beforeEscrow + amount);
  assert.equal(await pledge.totalLocked(pool.lpToken), beforeLiability + amount);
  assert.equal(await lp.allowance(core.signer.address, contractAddress), 0n);
  assert((await rpc.getBlock("latest")).timestamp < unlockAt, "Early check missed its window; resume against the saved deposit block.");
  await assert.rejects(pledge.withdraw.staticCall(id), isContractRevert);
  run.data.earlyWithdrawalRejected = true;
  await run.save();
  const waitDeadline = Date.now() + 5 * 60 * 1000;
  while ((await rpc.getBlock("latest")).timestamp < unlockAt) {
    if (Date.now() > waitDeadline) throw new Error(`Consensus time did not reach maturity within five minutes. Lock ${id} remains recoverable with testnet:withdraw; workflow not verified.`);
    console.log(`Lock ${id} holds real LP; waiting for testnet consensus timestamp ${unlockAt}.`);
    await new Promise(resolve => setTimeout(resolve, 10000));
  }
  await send(hre, core, run, "withdraw matured LP", await pledge.withdraw.populateTransaction(id, {}));
  assert.equal(await lp.balanceOf(core.signer.address), before);
  assert.equal(await lp.balanceOf(contractAddress), beforeEscrow);
  assert.equal(await pledge.totalLocked(pool.lpToken), beforeLiability);
  assert.equal((await pledge.locks(id)).withdrawn, true);
  await assert.rejects(pledge.withdraw.staticCall(id), isContractRevert);
  run.data.repeatedWithdrawalRejected = true;
  run.data.afterBalance = (await lp.balanceOf(core.signer.address)).toString();
  run.data.fullWorkflowVerified = true;
  run.data.completedAt = new Date().toISOString();
  await run.save();
  await fs.mkdir(path.join(root, "deployments"), { recursive: true });
  await fs.writeFile(path.join(root, "deployments/latest-proof.json"), JSON.stringify(run.data, null, 2) + "\n");
  console.log(`Real testnet deposit and withdrawal verified. Evidence: ${run.file}`);
}
main().catch(fail);
